# utils/config.py

# NETWORK
INTERFACE = "Wi-Fi"     # or "Ethernet"
CAPTURE_FILTER = "tcp"

# DETECTION
TIME_WINDOW = 5
PORT_THRESHOLD = 20

# DEFENSE
PORT_RANGE_START = 20000
PORT_RANGE_END = 60000

BLOCK_ATTACKER = True

# SERVICE
INTERNAL_SERVICE_PORT = 22

# LOGGING
LOG_FILE = "logs/system.log"
LOG_LEVEL = "INFO"